### PR TITLE
Milestone 7.1: Blog app - Add forms

### PR DESCRIPTION
**Pull request by Gardimy**
In this milestone, I added forms to my Blog app.

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
## Hi :raising_hand: :raising_hand: @Gardimy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





## Highlights :green_circle: 

- App is working on the browser :-1: 


## Required Changes ♻️

- Hi @Gardimy, you didn't push any file changes, so I'll just attach some issues to fix here:

- [ ] Each of the template file sizes is very large because you are making use of inline styling which is not a good habit. Let's kindly use assets pipeline. Rails pick up all styles neatly place at app/assets/stylesheets. Let's kindly fix this to render codebase clean.
- [ ] Let's kindly make sure codebase is efficient, extendable and a developer can easily contribute to your project. Right now there's no dedicated page to create a new post. You placed the form to create a new post at the user show page which is not meant for this specific. There should be two routes necessary to create a new post ie `resources :posts, only: [:new :create]` **NOT** `resources :posts, only: [:index, :show, :create]` as seen in your codebase. Even the create action is not in your PostsController class. The PostsController class should have methods corresponding to two routes in your routes.rb file. The logic of the current user creating a post should be remove in the views(:show) and instead place in the create action of the PostsController class. The template to create a new post should be found at app/views/posts/new.html.erb :+1: 
- [ ] Right now, Posts created are not display hence I can't even add a comment. After creating some posts I didn't see these posts at `http://localhost:3000/users/:id/posts` . Posts created are not save to the db. Let's kindly fix it.
- [ ] Two actions were added to create a comment for a post :+1: as requested(:new, :create). As pointed above, let's kindly make sure form to create a comment is at app/views/comments/new.html.erb and the routes required to create a comment should be `resources :comments, only: [:new, :create]`

_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gardimy** [comment]
Have you read the project requirements?

**Comment by Gardimy** [comment]
Have you read the project requirements?

**Review by OLIPLICHE — APPROVED** [review]
Hi @Gardimy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Applied the changes by the previous reviewer (✅)) 👏
- Populated the database 👏
- Forms have been created 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
